version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
workflows:
    build-and-test:
      jobs:
        - build-and-test
    build-deploy: # Make a workflow to build and deploy your project
      jobs:
        - build
        - deploy:
            requires:
              - build # Only run deploy job once the build job has completed
            filters:
              branches:
                only: master # Only deploy when the commit is on the Master branch
    steps:
      - checkout
      - aws-s3/sync:
          from: bucket
          to: 's3://daily-report-bucket'
          arguments: | # Optional arguments
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true # default is false


