version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  integration-test-1:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          from: bucket
          to: "s3://daily-report-bucket"
          overwrite: true
      - aws-s3/copy:
          from: bucket/build_asset.txt
          to: "s3://daily-report-bucket"

workflows:
